### ISSUE TITLE
Error on Setup of Cam

### ISSUE THREAD

**Issue by short4bmoney** [RenierM26/ha-ezviz#11]
Just updated to 0.0.2.5 and still getting an error. I'm unsure whether my configuration is correct, but I'm following the instructionss:

```
ezviz_cloud:
  cameras:
    E81680149:
      username: admin
      password: !secret ezviz_cam1_code
```

But I receive a series of errors reported in Configuration > Logs

> Logger: homeassistant.config_entries
> Source: custom_components/ezviz_cloud/__init__.py:146
> First occurred: 10:02:06 AM (1 occurrences)
> Last logged: 10:02:06 AM
>
> [...]
>
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/ezviz_cloud/__init__.py", line 91, in async_setup_entry
>     ezviz_client = await hass.async_add_executor_job(
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/ezviz_cloud/__init__.py", line 146, in _get_ezviz_client_instance
>     ezviz_client.login()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 308, in login
>     self._login()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 88, in _login
>     raise PyEzvizError("Can not login to API")
> pyezviz.client.PyEzvizError: Can not login to API

Is there any method to separately verify my credentials for the API?

**Comment by short4bmoney** [comment]
I think I missed a step, but now getting a different issue. Will report separately.
