### ISSUE TITLE
Unexpected error fetching ezviz_cloud data: Could not access Ezviz' API: HTTPSConnectionPool(host='ieu.ezvizlife.com', port=443)

### ISSUE THREAD

**Issue by helepeut** [RenierM26/ha-ezviz#16]
Hi !

New user on HomeAssistant, I tried your integration about 10 days ago using 0.0.2.X versions, with no luck.
So I used version 0.0.1.6 (previous code before complete rework I guess), and it was working.
Today, I tried your new version 0.0.2.7, hoping that I would manage to make it work, but still the same issues.

What I did (the "standard" user test ;-) - maybe it could help you) :
- updated my 0.0.1.6 config to align with 0.0.2.7 requirements
- installed the ezviz-cloud using hacs / checked that custom_compenents was updated with a new ezviz_cloud folder)
- added integration and set login / password
- restarted the server

Here are the errors/warnings in the log.

Warning (MainThread) [homeassistant.config_entries] Config entry for ezviz_cloud not ready yet. Retrying in 5 seconds

Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:31
Integration: Ezviz (documentation)
First occurred: 12:48:33 (43 occurrences)
Last logged: 13:52:13

Unexpected error fetching ezviz_cloud data: Could not access Ezviz' API: HTTPSConnectionPool(host='ieu.ezvizlife.com', port=443): Read timed out. (read timeout=15)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='ieu.ezvizlife.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 442, in get_detection_sensibility
    req = self._session.post("https://" + self._API_DOMAIN + API_BASE_TLD + API_ENDPOINT_DETECTION_SENSIBILITY_GET,
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='ieu.ezvizlife.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.EzvizClient.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 270, in load_cameras
    camera.load()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 36, in load
    self._detection_sensibility = self._client.get_detection_sensibility(self._serial, self._device['supportExt']['support_sensibility_adjust'])
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 448, in get_detection_sensibility
    raise PyEzvizError("Could not access Ezviz' API: " + str(e))
pyezviz.client.PyEzvizError: Could not access Ezviz' API: HTTPSConnectionPool(host='ieu.ezvizlife.com', port=443): Read timed out. (read timeout=15)

and the configuration.yaml :
stream:
ffmpeg:
camera:

ezviz_cloud:
  cameras:
    CAMERAID:
      username: admin
      password: PASSWORD
    CAMERAID:
      username: admin
      password: PASSWORD

Maybe I missed something, and if so, please excuse me.

PS : i tried to manually connect to ieu.ezvizlife.com with Internet Explorer, and it's ok (while redirected to https://euauth.ezvizlife.com/)

**Comment by RenierM26** [comment]
Hi @helepeut, 

You could try to increase the timeout on integration "options" page? Perhaps try 30 instead of 15.

I'm assuming your using the latest version? The timeout setting only works on the latest version.

**Comment by helepeut** [comment]
Hi @RenierM26 
Thanks a lot ! 
Such ashamed to not even have tried to change this value ! I have now the related entities, Thanks a lot ! (and thanks for all the work you do for the community).
Now I'm facing the Timeout Reading Image from haffmpeg. I'll re-read all your posts to find out what's happening ;-)

**Comment by helepeut** [comment]
So, now i don't have this issue anymore, but I don't figure how to get a picture using the entity card. 
If i click on it, I have access to the stream, and using the developer tools, I can have access to all the entity attributes, but the card stays empty.
Did you use the native card or a custom one ?

**Comment by helepeut** [comment]
@RenierM26 I finally made it work, simply by adding the camera-image and camera-view attributes in the card. Silly me !
Thanks !
