### ISSUE TITLE
_get_pagelist: EzvizError("Can't gather proper data. Max retries exceeded.")

### ISSUE THREAD

**Issue by klec00** [RenierM26/ha-ezviz#23]
After upgrading to 0.0.2.9, the  integration seems to have stopped working. I get the following error message in my log every 90 seconds:
````
2021-02-11 12:24:45 ERROR (MainThread) [custom_components.ezviz_cloud.coordinator] Unexpected error fetching ezviz_cloud data: Can't gather proper data. Max retries exceeded.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 325, in load_cameras
    devices = self.get_all_device_infos()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 364, in get_all_device_infos
    devices = self.get_page_list()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 794, in get_page_list
    return self._get_pagelist(
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _get_pagelist
    return self._get_pagelist(page_filter, json_key, max_retries + 1)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _get_pagelist
    return self._get_pagelist(page_filter, json_key, max_retries + 1)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _get_pagelist
    return self._get_pagelist(page_filter, json_key, max_retries + 1)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 117, in _get_pagelist
    raise PyEzvizError("Can't gather proper data. Max retries exceeded.")
pyezviz.client.PyEzvizError: Can't gather proper data. Max retries exceeded
````

I have three cameras registered. Two C3WN at home,  and one C6N that currently is offline (remote camera in my summer cottage), and I don't know if that is what is causing the problem...?

Running Home-Assistant core-2021.2.2 and supervisor-2021.02.6

**Comment by klec00** [comment]
Ok, idiot warning ahead. I had turned on 2FA in the EZViz app... Turning that off made it come back again.

**Comment by RenierM26** [comment]
Hi Klec00,

No problem. I have an idea on what to do to enable MFA support and will implement it in a few weeks. Just one API endpoint I need to find before my idea can work. 

Thanks for the feedback.
