### ISSUE TITLE
Component seems broken after upgrade to 0.0.3.2

### ISSUE THREAD

**Issue by marcob79** [RenierM26/ha-ezviz#25]
After upgrade to 0.0.3.2 and restart I'm no more able to see the video stream and I got several errors in the log

Logger: homeassistant.config_entries
Source: custom_components/ezviz_cloud/__init__.py:149
First occurred: 9:15:33 PM (1 occurrences)
Last logged: 9:15:33 PM

Error setting up entry xxxxxx for ezviz_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0xa8934760>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='euauth.ezvizlife.com', port=443): Max retries exceeded with url: /doLogin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa8934760>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 74, in _login
    req = self._session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='euauth.ezvizlife.com', port=443): Max retries exceeded with url: /doLogin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa8934760>: Failed to establish a new connection: [Errno -3] Try again'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 91, in async_setup_entry
    ezviz_client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/__init__.py", line 149, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 480, in login
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 104, in _login
    raise PyEzvizError("Can not login to API") from err
pyezviz.client.PyEzvizError: Can not login to API

**Comment by RenierM26** [comment]
Hi @marcob79 ,

This looks like a connection or login issue. Could you please double check your ezviz cloud login details?

**Comment by marcob79** [comment]
I didn't change them since a long time. Anyway I checked and they are fine.
After that I just try a restart and now is fine... Very strange
