### ISSUE TITLE
Integration fails

### ISSUE THREAD

**Issue by Wolk9** [RenierM26/ha-ezviz#35]
Hi,
After thoroughly reading the notes of your integration and followed the right order of steps (HACS install, configuration.yaml camera add, restart, add integration, login in and go), i got the following error log details:

`Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:31
Integration: Ezviz (documentation)
First occurred: 8:48:11 PM (6 occurrences)
Last logged: 8:51:01 PM

Unexpected error fetching ezviz_cloud data: Can't gather proper data. Max retries exceeded.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 320, in load_cameras
    devices = self._get_all_device_infos()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 359, in _get_all_device_infos
    devices = self._get_page_list()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 778, in _get_page_list
    return self._api_get_pagelist(
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 117, in _api_get_pagelist
    raise PyEzvizError("Can't gather proper data. Max retries exceeded.")
pyezviz.client.PyEzvizError: Can't gather proper data. Max retries exceeded.
`

What am I doing wrong, and more important: what can I do about it? 

Best Regards,
Wolk9

**Comment by avol-io** [comment]
see https://github.com/RenierM26/ha-ezviz/issues/23
