### ISSUE TITLE
Unexpected error fetching ezviz_cloud data: Can't gather proper data. Max retries exceeded.

### ISSUE THREAD

**Issue by avol-io** [RenierM26/ha-ezviz#41]
021-03-04 18:14:56 ERROR (MainThread) [custom_components.ezviz_cloud.coordinator] Unexpected error fetching ezviz_cloud data: Can't gather proper data. Max retries exceeded.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.ezviz_client.load_cameras()
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 320, in load_cameras
    devices = self._get_all_device_infos()
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 359, in _get_all_device_infos
    devices = self._get_page_list()
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 778, in _get_page_list
    return self._api_get_pagelist(
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  [Previous line repeated 1 more time]
  File "/data/data/com.termux/files/home/.homeassistant/deps/lib/python3.8/site-packages/pyezviz/client.py", line 117, in _api_get_pagelist
    raise PyEzvizError("Can't gather proper data. Max retries exceeded.")
pyezviz.client.PyEzvizError: Can't gather proper data. Max retries exceeded.

some hints as to where I went wrong?

**Comment by avol-io** [comment]
https://github.com/RenierM26/ha-ezviz/issues/23
