### ISSUE TITLE
Incorrect Captha Code error - v 0.0.4.4

### ISSUE THREAD

**Issue by TrainHeartnet92** [RenierM26/ha-ezviz#42]
Hi, i'm using this integration to use my new Ezviz C6N but not working.
I've this setup:
Installed via HACS v0.0.4.4
HA supervisor-2021.03.04
HA core-2021.3.2

setup camera.yaml
```
camera:
    username: EMAIL
    password: PASSWORD_EZVIZ
    cameras:
      N_CAMERA:
        username: admim
        password: PASSWORD_CAMERA
```

I've this error:

`2021-03-06 12:57:03 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry EMAIL for ezviz_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 56, in async_setup_entry
    ezviz_client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/__init__.py", line 119, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 480, in login
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 90, in _login
    raise PyEzvizError("Login error: Incorrect Captcha code")
pyezviz.client.PyEzvizError: Login error: Incorrect Captcha code
2021-03-06 12:57:03 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry EZVIZ_USERNAME for ezviz_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 56, in async_setup_entry
    ezviz_client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/__init__.py", line 119, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 480, in login
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 90, in _login
    raise PyEzvizError("Login error: Incorrect Captcha code")`

How can i solve?
Thank you
Luigi

**Comment by TrainHeartnet92** [comment]
I uninstall and install the integration, delete everything and now it load all the information.
I've another problem: it set the local_ip as 0.0.0.0 so i can't loading the streaming.
How can i solve?

**Comment by RenierM26** [comment]
Hi @TrainHeartnet92,

Have you tried the latest version?

**Comment by RenierM26** [comment]
Stale issue. Zero ip should be fixed in latest release.
