### ISSUE TITLE
varius error

### ISSUE THREAD

**Issue by xericcardo** [RenierM26/ha-ezviz#46]
Hi
I have tried various ways but I cannot connect the webcam model C6N. These are the errors that are put in HA

Logger: custom_components.ezviz_cloud.coordinator
Source: helpers/update_coordinator.py:173
Integration: Ezviz (documentation)
First occurred: 20 marzo 2021, 20:04:46 (42 occurrences)
Last logged: 20 marzo 2021, 20:58:33

Error fetching ezviz_cloud data: Invalid response from API: Can't gather proper data. Max retries exceeded.

and

Logger: homeassistant.config_entries
Source: custom_components/ezviz_cloud/__init__.py:135
First occurred: 20 marzo 2021, 20:59:58 (1 occurrences)
Last logged: 20 marzo 2021, 20:59:58

Error setting up entry xericcardo@gmail.com for ezviz_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5f382715e0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='euauth.ezvizlife.com', port=443): Max retries exceeded with url: /doLogin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f382715e0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 73, in async_setup_entry
    ezviz_client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/__init__.py", line 135, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 536, in login
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 74, in _login
    req = self._session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='euauth.ezvizlife.com', port=443): Max retries exceeded with url: /doLogin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5f382715e0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by nguyenbabao** [comment]
Here is the solution I have tried and succeeded.
After you add intergration ezviz, please login to https://ieu.ezvizlife.com/ with IE.
Then open the configuration / integrations again, you will see the camera is recognized.

**Comment by xericcardo** [comment]
hello
Thanks for the reply I did as you explained .
The integration sees the camera but does not detect device or entity.

**Comment by nguyenbabao** [comment]
What do you mean by this?
![image](https://user-images.githubusercontent.com/68863522/111978159-32b2b700-8b36-11eb-9549-9da9bb08c519.png)
![image](https://user-images.githubusercontent.com/68863522/111978210-42320000-8b36-11eb-8627-1bbf90607dd1.png)

**Comment by xericcardo** [comment]
I don't see anything you see

**Comment by nguyenbabao** [comment]
i think need disable this
![image](https://user-images.githubusercontent.com/68863522/111981401-38aa9700-8b3a-11eb-8ac7-e0d6a227da46.png)

**Comment by xericcardo** [comment]
Now I see the entities , I try in these days to work on it to see if everything works.
Thanks 1000
