### ISSUE TITLE
integration fails to login due to captcha failing?

### ISSUE THREAD

**Issue by Pukington** [RenierM26/ha-ezviz#5]
Hi,

I've installed the integration via HACS using the correct email address/password.

My configuration.yaml:
```
stream:
ffmpeg:
camera:
ezviz_cloud:
  cameras:
    E56407678:
      username: admin
      password: xxx
```

My hassio log:

```
Logger: homeassistant.config_entries
Source: custom_components/ezviz_cloud/__init__.py:142
First occurred: 12:20:33 AM (1 occurrences)
Last logged: 12:20:33 AM

Error setting up entry xxx@gmail.com for ezviz_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 79, in async_setup_entry
    ezviz_client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/__init__.py", line 142, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 301, in login
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 80, in _login
    raise PyEzvizError("Login error: Incorrect Captcha code")
pyezviz.client.PyEzvizError: Login error: Incorrect Captcha code
```

I've logged into the web based ezviz site with the same username/password, entered the captcha on the site and can access my camera remotely using:  https://i.ezvizlife.com/user/userAction!displayUserInfo.action

The camera was setup initially via my ios device and still works flawlessly with the app.

Any idea how I can get around this?  I'd appreciate any input as it'd be ace to get this working!

**Comment by Pukington** [comment]
Weirdly this has sorted itself.

I removed the integration, commented out the config.yaml entry, reinstalled and uncommented last night after posting this thread and it still didn't work.

I checked again this morning and it still wasn't working.

Check again now and it's working absolutely fine, I've got a picture entity card in lovelace and it's forwarded to homekit all fine and dandy.

I do have an error in my log but everything seems to be working as it should be, here's my error:

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:155
First occurred: 11:20:29 AM (11 occurrences)
Last logged: 3:36:30 PM

Error setting up entry xxx@gmail.com for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 319, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```
