### ISSUE TITLE
timePlanInfos error while setting the ezviz_cloud platform

### ISSUE THREAD

**Issue by powro** [RenierM26/ha-ezviz#53]
I started to receive the below error after upgrade to the latest version (earlier using couple of months old one). Interesting is that it pops up even if i do not configure any camera (only the main user account). I have one camera with notification schedule configured (if this is related), however disabling the schedule does not help here.

```
Unexpected error fetching ezviz_cloud data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 36, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 28, in _update_data
    cameras = self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 366, in load_cameras
    cameras.append(camera.status())
  File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 140, in status
    self._device.get("timePlanInfos")[1].get("enable")
TypeError: 'NoneType' object is not subscriptable
```
Any ideas what may be the issue?

**Comment by RenierM26** [comment]
Hi @powro,

Found the problem. It should work with the latest release v.0.0.6.0. 

Would you trying the latest release?

**Comment by powro** [comment]
Works perfect! Thank you @RenierM26
