### ISSUE TITLE
Camera not working, local IP 0.0.0.0

### ISSUE THREAD

**Issue by 1800Zeta** [RenierM26/ha-ezviz#58]
Hi,

I have removed the integration and reinstalled the HACS plugin but I am not able to view the camera, when I look the RSTP feed appears to be using the local ip of 0.0.0.0 which I can only assume it's received via the API or similar. I am running v0.0.6.0. I cannot add a second instance of the integration which I used to do to add the camera credentials. 

Thanks
Mark

**Comment by 1800Zeta** [comment]
I have an LC1 camera, and it's the camera that isn't coming up. Everything else appears to work fine, it's picking up the external IP and other attributes (entities), but the camera aspect stopped. Only obvious thing I can see is that it has local_ip as 0.0.0.0

**Comment by 1800Zeta** [comment]
I have gone back to version 0.0.5.7, adding the integration then detects the camera and adds it. The local_ip attribute is still 0.0.0.0 and not seeing the camera but at least it didn't error adding it.

**Comment by 1800Zeta** [comment]
When re-adding v0.0.6.0, I add the integration, enter username, password and URL (eu) which all works. HA then discovers the camera, so I click configure, enter the password (which I know is correct, copy/paste from notepad and worked with previous versions), and then get the error:

Discovered Ezviz Camera
Enter RTSP credentials for Ezviz camera <<Serial Nunber>> with IP as 0.0.0.0

Serial number is correct.

**Comment by 1800Zeta** [comment]
Noticed this in the logs when adding it again:

```
Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:28
Integration: Ezviz (documentation)
First occurred: 20:41:58 (1 occurrences)
Last logged: 20:41:58

Unexpected error fetching ezviz_cloud data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 36, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 28, in _update_data
    cameras = self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 334, in load_cameras
    devices = self._get_all_device_infos()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 391, in _get_all_device_infos
    result[device["deviceSerial"]]["timePlanInfos"] = devices.get(
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by RenierM26** [comment]
Hi @1800Zeta ,

I need some info in order to resolve this issue.

Would one you be able to share a json dump? (Just find and replace the camera serial numbers in the output for privacy reasons it shouldn't be shared on a public forum)

1) Just login to this site first, before opening the url above (assuming EU server here):

https://ieu.ezvizlife.com/

2) You should be able to open this page in IE or Safari. Is should automatically start downloading a .json file.

https://apiieu.ezvizlife.com/v3/userdevices/v1/resources/pagelist?groupId=-1&limit=30&offset=0&filter=CLOUD%2CTIME_PLAN%2CCONNECTION%2CSWITCH%2CSTATUS%2CWIFI%2CNODISTURB%2CKMS%2CP2P%2CTIME_PLAN%2CCHANNEL%2CVTM%2CDETECTOR%2CFEATURE%2CUPGRADE%2CVIDEO_QUALITY%2CQOS

**Comment by 1800Zeta** [comment]
Thank you for the pointers! I was trying to find this info. I replaced the SN with "SERIALNO"
```
{
    "CLOUD": {
        "3a7093bce3c64f26aafd3a68c62d1c7c": {
            "deviceSerial": "SERIALNO",
            "channelNo": 1,
            "status": 2,
            "totalDays": 7,
            "validDays": -88
        }
    },
    "DETECTOR": {},
    "VTM": {
        "3a7093bce3c64f26aafd3a68c62d1c7c": {
            "domain": "vtmtxeu.ezvizlife.com",
            "externalIp": "49.51.130.91",
            "internalIp": null,
            "port": 10554,
            "forceStreamType": 0,
            "isBackup": 0
        }
    },
    "P2P": {
        "SERIALNO": [
            {
                "ip": "34.254.0.145",
                "port": 6000
            },
            {
                "ip": "34.249.121.84",
                "port": 6000
            }
        ]
    },
    "CONNECTION": {
        "SERIALNO": {
            "localIp": "0.0.0.0",
            "netIp": "92.19.209.203",
            "localRtspPort": 0,
            "netRtspPort": 0,
            "localCmdPort": 9010,
            "netCmdPort": 37793,
            "localStreamPort": 9020,
            "netHttpPort": 0,
            "localHttpPort": 0,
            "netStreamPort": 35739,
            "netType": 3,
            "wanIp": null,
            "upnp": false
        }
    },
    "KMS": {
        "SERIALNO": {
            "secretKey": "SECRETKEY",
            "version": "101"
        }
    },
    "STATUS": {
        "SERIALNO": {
            "diskNum": 1,
            "diskState": "0---------------",
            "globalStatus": 1,
            "pirStatus": 0,
            "isEncrypt": 1,
            "encryptPwd": "10e10a38de30454dad0417c523aba2bd",
            "upgradeAvailable": 0,
            "upgradeProcess": 0,
            "upgradeStatus": 2,
            "alarmSoundMode": 2,
            "optionals": {
                "latestUnbandTime": "1609599216343",
                "updateCode": "0",
                "diskHealth": "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1",
                "OnlineStatus": "1",
                "AlgorithmInfo": "[{\"SubType\":\"0\",\"channel\":1,\"Value\":\"1\"}]",
                "timeZone": "UTC",
                "language": "ENG",
                "cloudChannelList": "[{\"channel\":0,\"status\":0,\"type\":0},{\"channel\":1,\"status\":0,\"type\":0}]",
                "Alarm_Light": "{  \"luminance\": 100 }",
                "diskCapacity": "121942,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1",
                "wanIp": "92.19.209.203",
                "kms_version": "100",
                "daylightSavingTime": "1",
                "timeFormat": "0",
                "tzCode": "140",
                "superState": "0",
                "voiceIndex": "0",
                "latestUnbindTime": "1609599216343",
                "lastUpgradeTime": "1609599645524"
            }
        }
    },
    "TIME_PLAN": {
        "SERIALNO": [
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 1,
                "enable": 1,
                "weekPlans": [
                    {
                        "weekDay": "0",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    },
                    {
                        "weekDay": "1",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    },
                    {
                        "weekDay": "2",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    },
                    {
                        "weekDay": "3",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    },
                    {
                        "weekDay": "4",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    },
                    {
                        "weekDay": "5",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    },
                    {
                        "weekDay": "6",
                        "timePlan": [
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            },
                            {
                                "startTime": "0:0",
                                "endTime": "24:0"
                            }
                        ]
                    }
                ]
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 2,
                "enable": 0,
                "weekPlans": [
                    {
                        "weekDay": "0",
                        "timePlan": []
                    },
                    {
                        "weekDay": "1",
                        "timePlan": []
                    },
                    {
                        "weekDay": "2",
                        "timePlan": []
                    },
                    {
                        "weekDay": "3",
                        "timePlan": []
                    },
                    {
                        "weekDay": "4",
                        "timePlan": []
                    },
                    {
                        "weekDay": "5",
                        "timePlan": []
                    },
                    {
                        "weekDay": "6",
                        "timePlan": []
                    }
                ]
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 4,
                "enable": -1,
                "weekPlans": [
                    {
                        "weekDay": "0",
                        "timePlan": [
                            {
                                "startTime": "-1:65",
                                "endTime": "-1:65"
                            }
                        ]
                    },
                    {
                        "weekDay": "1",
                        "timePlan": []
                    },
                    {
                        "weekDay": "2",
                        "timePlan": []
                    },
                    {
                        "weekDay": "3",
                        "timePlan": []
                    },
                    {
                        "weekDay": "4",
                        "timePlan": []
                    },
                    {
                        "weekDay": "5",
                        "timePlan": []
                    },
                    {
                        "weekDay": "6",
                        "timePlan": []
                    }
                ]
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 5,
                "enable": -1,
                "weekPlans": [
                    {
                        "weekDay": "0",
                        "timePlan": []
                    },
                    {
                        "weekDay": "1",
                        "timePlan": []
                    },
                    {
                        "weekDay": "2",
                        "timePlan": []
                    },
                    {
                        "weekDay": "3",
                        "timePlan": []
                    },
                    {
                        "weekDay": "4",
                        "timePlan": []
                    },
                    {
                        "weekDay": "5",
                        "timePlan": []
                    },
                    {
                        "weekDay": "6",
                        "timePlan": []
                    }
                ]
            }
        ]
    },
    "CHANNEL": {
        "3a7093bce3c64f26aafd3a68c62d1c7c": {
            "channelDeviceSerial": null,
            "channelNo": 1,
            "privacyStatus": 0,
            "powerStatus": 0,
            "globalStatus": 0,
            "signalStatus": 1
        }
    },
    "QOS": {
        "SERIALNO": {
            "domain": "vtmtxeu.ezvizlife.com",
            "externalIp": "49.51.130.91",
            "internalIp": null,
            "port": 10554,
            "memo": "按国家路由(stsvtmtxeu)",
            "idcType": "DUAL",
            "isBackup": 0
        }
    },
    "meta": {
        "code": 200,
        "message": "操作成功",
        "moreInfo": {}
    },
    "NODISTURB": {
        "SERIALNO": {
            "alarmEnable": 0,
            "callingEnable": 0
        }
    },
    "FEATURE": {},
    "UPGRADE": {
        "SERIALNO": {
            "isNeedUpgrade": 0,
            "upgradePackageInfo": null
        }
    },
    "SWITCH": {
        "SERIALNO": [
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 1,
                "enable": true
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 2,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 3,
                "enable": true
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 7,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 10,
                "enable": true
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 21,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 22,
                "enable": true
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 29,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 300,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 301,
                "enable": true
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 302,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 303,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 304,
                "enable": false
            },
            {
                "deviceSerial": "SERIALNO",
                "channelNo": 0,
                "type": 305,
                "enable": true
            }
        ]
    },
    "VIDEO_QUALITY": {
        "3a7093bce3c64f26aafd3a68c62d1c7c": [
            {
                "streamType": 2,
                "videoLevel": 1
            },
            {
                "streamType": 1,
                "videoLevel": 2
            },
            {
                "streamType": 1,
                "videoLevel": 3
            }
        ]
    },
    "page": {
        "offset": 0,
        "limit": 30,
        "totalResults": 0,
        "hasNext": false
    },
    "resourceInfos": [
        {
            "resourceId": "19b6b29658a84d14a7cb0489924fc339",
            "resourceName": "LC1(SERIALNO)",
            "deviceSerial": "SERIALNO",
            "superDeviceSerial": "SERIALNO",
            "localIndex": "0",
            "shareType": 0,
            "permission": -1,
            "resourceType": 0,
            "resourceCover": "",
            "isShow": 1,
            "videoLevel": 0,
            "streamBizUrl": "biz=1",
            "groupId": -1
        },
        {
            "resourceId": "3a7093bce3c64f26aafd3a68c62d1c7c",
            "resourceName": "LC1(SERIALNO)",
            "deviceSerial": "SERIALNO",
            "superDeviceSerial": "SERIALNO",
            "localIndex": "1",
            "shareType": 0,
            "permission": -1,
            "resourceType": 50,
            "resourceCover": "https://ieu.ezvizlife.com/assets/imgs/public/homeDevice.jpeg",
            "isShow": 1,
            "videoLevel": 3,
            "streamBizUrl": "biz=1",
            "groupId": -1
        }
    ],
    "WIFI": {
        "SERIALNO": {
            "netName": "wlan0",
            "netType": "wireless",
            "address": "192.168.253.10",
            "mask": "255.255.255.0",
            "gateway": "192.168.253.254",
            "signal": 92,
            "ssid": "InternetOTings"
        }
    },
    "deviceInfos": [
        {
            "name": "LC1(SERIALNO)",
            "deviceSerial": "SERIALNO",
            "fullSerial": "CS-LC1-A0-1B2WPFRL0120200424CCTWSERIALNO",
            "deviceType": "CS-LC1-A0-1B2WPFRL",
            "devicePicPrefix": "https://devpic.ezvizlife.com/device/image/CS-LC1-A0-1B2WPFRL/",
            "version": "V5.2.6 build 200804",
            "supportExt": "{\"44\":\"0\",\"88\":\"1\",\"46\":\"1\",\"26\":\"0\",\"48\":\"1\",\"28\":\"1\",\"152\":\"1\",\"297\":\"1\",\"232\":\"1\",\"298\":\"1\",\"233\":\"1\",\"113\":\"1\",\"234\":1,\"236\":\"1\",\"237\":\"1\",\"93\":\"0\",\"51\":\"0\",\"30\":\"0\",\"96\":\"2\",\"31\":\"0\",\"97\":\"1\",\"10\":\"1\",\"11\":\"1\",\"12\":\"1\",\"13\":\"3\",\"14\":\"1\",\"15\":\"1\",\"37\":\"1\",\"59\":\"1\",\"16\":\"16-9\",\"141\":\"0\",\"1\":\"1\",\"2\":\"3\",\"3\":\"1\",\"4\":\"1\",\"301\":\"1\",\"5\":\"0\",\"6\":\"0\",\"7\":\"1\",\"106\":\"2\",\"8\":\"1\",\"9\":\"1\",\"61\":\"1\",\"62\":\"1\",\"63\":\"1\"}",
            "status": 1,
            "userDeviceCreateTime": "2021-01-02 14:53:41",
            "channelNumber": 1,
            "hik": false,
            "deviceCategory": "IPC",
            "deviceSubCategory": "LC1",
            "ezDeviceCapability": "{\"232\":\"0\",\"233\":\"0\",\"234\":1,\"268\":\"1\",\"30\":\"0\",\"31\":\"0\",\"262\":\"1\",\"175\":\"1\",\"263\":\"0\"}",
            "customType": "CS-LC1-A0-1B2WPFRL",
            "offlineTime": "2021-03-16 08:36:01",
            "offlineNotify": 0,
            "instructionBook": "http://devpic.ezvizlife.com/device/image/CS-LC1-A0-1B2WPFRL/instruction.jpeg",
            "authCode": "2-2-V2.0.2",
            "userName": "jygkeo",
            "riskLevel": 0,
            "offlineTimestamp": 1615883761000
        }
    ]
}
```

**Comment by RenierM26** [comment]
Hi @1800Zeta,

Are you using a supervised hassio install? Or a custom one on your own flavor of Linux? I have a suspicion that Ezviz uses nodejs (or some other java platform) and returns data in specific format based on the agent string. (Basically how a web client identifies itself)

Have you tried running pyezviz (the api behind the integration) from a MAC or Windows environment? Might confirm my suspicion. 

pyezviz -u username@domain -p PASSWORD devices status

If this turns out to be the case then I'll just hardcode the android/generic user agent string in the api.

**Comment by 1800Zeta** [comment]
I am running the VMWare image, supervised OS

Operating System
Home Assistant OS 5.13

I will try and get hold of pyezviz and see what happens.

**Comment by 1800Zeta** [comment]
I get the following on a Windows machine:
```
      serial            name  status device_category device_sub_category sleep  privacy  audio  ir_led  state_led local_ip  local_rtsp_port detection_sensibility battery_level  alarm_schedules_enabled  alarm_notify  Motion_Trigger
0  SERIALNO LC1(SERIALNO)       1             IPC                 LC1  None    False   True    True       True  0.0.0.0                0                     1          None                    False          True               0
```

**Comment by RenierM26** [comment]
@1800Zeta,

Thanks. The coordinator error could be caused by user agent string. I'll investigate further why ip address from WiFi info's isn't populated.

**Comment by RenierM26** [comment]
@1800Zeta,

Found and fixed the issue. Would you mind testing? You might just need to "refresh information" if using HACS.

**Comment by 1800Zeta** [comment]
Updated, camera detected with correct IP and successfully added to HA. Thank you for the fast fix.

**Comment by RenierM26** [comment]
Excellent. Thank you for the feedback!
