### ISSUE TITLE
Unexpected error when adding integration

### ISSUE THREAD

**Issue by AcidSleeper** [RenierM26/ha-ezviz#71]
Hey

Using latest Core 2021.5.5and latest OS.
Trying to add the integration Ezviz from Configuration --> Integration gives me this error:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/ezviz/config_flow.py", line 189, in async_step_user
    return await self._validate_and_create_auth(user_input)
  File "/usr/src/homeassistant/homeassistant/components/ezviz/config_flow.py", line 73, in _validate_and_create_auth
    await self.hass.async_add_executor_job(_get_ezviz_client_instance, data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ezviz/config_flow.py", line 46, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 509, in login
    return self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 124, in _login
    self._token["session_id"] = str(json_result["loginSession"]["sessionId"])
KeyError: 'loginSession'`

Logincredentials is correct and if I try "the wrong password" it gives me "Invalid authentication" so what to do?
Im using no yaml i configuration.yaml. Right/wrong?

**Comment by RenierM26** [comment]
Hi @AcidSleeper,

1) Check MFA is disabled on your account. (You can re-enable after setting up the integration)
2) Your login url could be incorrect. Russian users need to pick the url with .ru domain. (It's an isolated region when it comes to ezviz)

**Comment by AcidSleeper** [comment]
That worked! Thanks!
