### ISSUE TITLE
Unexpected error fetching ezviz_cloud data: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by pete-leese** [RenierM26/ha-ezviz#84]
Have been getting the following error in my logs.

I am running latest version of HA and ezviz - I have a DB1 doorbell.

Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:32
Integration: Ezviz(Beta)
First occurred: 13:06:31 (7 occurrences)
Last logged: 21:01:16

Unexpected error fetching ezviz_cloud data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 38, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 32, in _update_data
    return self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 398, in load_cameras
    devices = self._get_all_device_infos()
  File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 470, in _get_all_device_infos
    result[device["deviceSerial"]]["cloudInfos"] = devices.get(
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by RenierM26** [comment]
Hi @pete-leese,

I have removed the cloudinfos section in the latest api release. It's not used in the HA integration and has been behaving sporadic.

v0.0.7.7

**Comment by pete-leese** [comment]
looks good thanks - I will close this !
