### ISSUE TITLE
Unexpected exception while login during extension setup

### ISSUE THREAD

**Issue by FraBoCH** [RenierM26/ha-ezviz#95]
I used the extension for several months without any glitch. Since a few days, home assistant was unable to access the stream of my two cameras and found session error in the log. I removed the integration completely and tried to setup everything again from scratch.

But I'm still unable to login due to the following unexpected error: 

`2021-11-13 16:59:20 ERROR (MainThread) [custom_components.ezviz_cloud.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/ezviz_cloud/config_flow.py", line 203, in async_step_user
return await self._validate_and_create_auth(user_input)
File "/config/custom_components/ezviz_cloud/config_flow.py", line 82, in _validate_and_create_auth
ezviz_token = await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ezviz_cloud/config_flow.py", line 56, in _get_ezviz_client_instance
ezviz_token = ezviz_client.login()
File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 576, in login
return self._login(account=self.account, password=self.password)
File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 135, in _login
self._token["session_id"] = str(json_result["loginSession"]["sessionId"])
KeyError: 'loginSession'`

I'm tryint to connect to apiieu.ezvizlife.com

**Comment by FraBoCH** [comment]
I found out the root cause by trying to login manually on apiieu.ezvizlife.com: it's the 2 step authentication! 2 step authentication seems not to be supported yet, so it must be disabled in order to use this integration.
