### ISSUE TITLE
List index out of range after latest update

### ISSUE THREAD

**Issue by fiorentino77** [RenierM26/ha-ezviz#96]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:32
Integration: Ezviz(Beta)
First occurred: 16:02:53 (58 occurrences)
Last logged: 17:17:45

Unexpected error fetching ezviz_cloud data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 38, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 32, in _update_data
    return self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 433, in load_cameras
    self._cameras[device] = EzvizCamera(self, device, data).status()
  File "/usr/local/lib/python3.9/site-packages/pyezviz/camera.py", line 139, in status
    "alarm_schedules_enabled": self._is_alarm_schedules_enabled(),
  File "/usr/local/lib/python3.9/site-packages/pyezviz/camera.py", line 110, in _is_alarm_schedules_enabled
    [
IndexError: list index out of range

**Comment by RenierM26** [comment]
Hi @fiorentino77,

Added fix for this. Could you please try v 0.0.8.5?

**Comment by Shamshala** [comment]
@RenierM26 Same error for me, even for v0.0.8.6.

**Comment by Shamshala** [comment]
@RenierM26 Same error for me, even on v0.0.8.6.

**Comment by RenierM26** [comment]
Hi @Shamshala and @fiorentino77,

Please try the latest release v0.0.8.8. It should fix this problem.

**Comment by RenierM26** [comment]
Hi,

I found another issue reported by users not using the eu ezviz domain. Hopefully all issues should be resolved with 0.0.9.0

Sorry for all the inconvenience.

**Comment by Shamshala** [comment]
> Hi @Shamshala and @fiorentino77,
> 
> Please try the latest release v0.0.8.8. It should fix this problem.

Sorry for the delay, actually even v0.0.8.7 fixed the issue.
